require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TpnsExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  pod 'react-native-tpns', :path => '../..'

  # Enables Flipper.
  use_flipper!({ 'Flipper' => '0.87.0' })
  post_install do |installer|
    react_native_post_install(installer)
  end
end
